name: grade_plus_plus
description: The mobile app for the project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^3.0.0
  url_launcher: ^5.4.1
  file_picker: ^1.4.3+2
  shared_preferences: ^0.5.6
  connectivity: ^0.4.6+1
  json_annotation: ^3.0.1
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.7.2
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/warning.png
    - assets/clock.png
    - assets/fireworks.png
    - assets/baby.png

# Run 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_square.png"
